name: Backend Checks (Windows)
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  backend-checks:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    # Setup Node.js and build frontend (embedded into Ivy)
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install frontend deps
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
      
    # Update workloads
    - name: Update .NET workloads
      run: dotnet workload update
    
    # Check code formatting
    - name: Check code formatting
      run: dotnet format --verify-no-changes
    
    # Build solution
    - name: Build solution
      run: dotnet build --configuration Release
    
    # Run tests
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      